use TFM_Archive
go

CREATE UNIQUE CLUSTERED INDEX [idx_ArchivingDataProcessing] ON [core].[ArchivingDataProcessing](AppDataType ASC, workflowId ASC, Tbl ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE CLUSTERED INDEX [idx_ArchivingDataProcessing] ON [core].[ArchivingDataProcessing_History](AppDataType ASC, workflowId ASC, Tbl ASC, LastDate ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE UNIQUE CLUSTERED INDEX [idx_DataArchivingAndPurgingConfig] ON [core].[DataArchivingAndPurgingConfig](AppDataType ASC, workflowId ASC, Tbl ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE UNIQUE CLUSTERED INDEX [idx_ExpiredArchivedDataProcessing] ON [core].[ExpiredArchivedDataProcessing](AppDataType ASC, workflowId ASC, Tbl ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE CLUSTERED INDEX [idx_ExpiredArchivedDataProcessing] ON [core].[ExpiredArchivedDataProcessing_History](AppDataType ASC, workflowId ASC, Tbl ASC, LastDate ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
