use TFM_Archive
go

CREATE NONCLUSTERED INDEX [idx_Activity_tranStepId] ON [tfm].[Activity](tranStepId ASC, timestamp ASC) 
INCLUDE (activityId)
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_Activity_timestamp] ON [tfm].[Activity](timestamp ASC) 
INCLUDE (tranStepId)
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [idx_FileLoad_lastModified] ON [tfm].[FileLoadHistory](lastModified ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE CLUSTERED INDEX [idx_loadId] ON [tfm].[FileLoadHistory](loadId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [idx_LoadError] ON [tfm].[LoadError](loadId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [idx_LoadErrorHistory] ON [tfm].[LoadErrorHistory](loadId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [idx_LoggerError] ON [tfm].[LoggerError](loadId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [idx_LoggerErrorHistory] ON [tfm].[LoggerErrorHistory](loadId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [idx_correlationId] ON [tfm].[Request](correlationId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE UNIQUE NONCLUSTERED INDEX [idx_transactionId] ON [tfm].[Request](timestamp ASC, transactionId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE UNIQUE CLUSTERED INDEX [PK_transactionId_KeyAttr] ON [tfm].[RequestKeyAttributes](keyName ASC, keyValue ASC, transactionId ASC) 
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
CREATE NONCLUSTERED INDEX [IX_Step_transactionId] ON [tfm].[Step](transactionId ASC) 
INCLUDE (tranStepId)
WITH (PAD_INDEX = OFF, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, SORT_IN_TEMPDB = OFF) ON [PRIMARY];
 
